services:
  postgres:
    image: postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  postgres-vol:

# docker exec -it nunes-sports-postgres-1 psql -U postgres
# CREATE DATABASE nunes_sports
